#!/bin/bash
#
# Setup Databricks secrets for Neo4j UC JDBC OAuth Connection
# Reads credentials from .env.oauth (generated by setup-keycloak-env.sh)
# and creates secrets in the oauth-neo4j-uc-creds scope
#

set -e

SCOPE_NAME="oauth-neo4j-uc-creds"
ENV_FILE=".env.oauth"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# Check for .env.oauth file
if [[ ! -f "$ENV_FILE" ]]; then
    log_error ".env.oauth file not found"
    echo "Generate it from a Keycloak deployment.json:"
    echo "  ./setup-keycloak-env.sh /path/to/.deployment.json neo4j-host"
    exit 1
fi

# Check for databricks CLI
if ! command -v databricks &> /dev/null; then
    log_error "Databricks CLI not found"
    echo "Install with: pip install databricks-cli"
    echo "Or: brew install databricks"
    exit 1
fi

# Load .env.oauth file
log_info "Loading credentials from $ENV_FILE"
set -a
source "$ENV_FILE"
set +a

# Validate required variables
missing=()
[[ -z "$NEO4J_HOST" ]] && missing+=("NEO4J_HOST")
[[ -z "$OAUTH_TOKEN_ENDPOINT" ]] && missing+=("OAUTH_TOKEN_ENDPOINT")
[[ -z "$OAUTH_CLIENT_ID" ]] && missing+=("OAUTH_CLIENT_ID")
[[ -z "$OAUTH_CLIENT_SECRET" ]] && missing+=("OAUTH_CLIENT_SECRET")
[[ -z "$UC_CONNECTION_NAME" ]] && missing+=("UC_CONNECTION_NAME")
[[ -z "$JDBC_JAR_PATH" ]] && missing+=("JDBC_JAR_PATH")

if [[ ${#missing[@]} -gt 0 ]]; then
    log_error "Missing required variables in .env.oauth: ${missing[*]}"
    exit 1
fi

# Create secret scope (ignore error if already exists)
log_info "Creating secret scope: $SCOPE_NAME"
if databricks secrets create-scope "$SCOPE_NAME" 2>/dev/null; then
    log_info "Secret scope created"
else
    log_warn "Secret scope already exists (or failed to create)"
fi

# Function to set a secret
set_secret() {
    local key=$1
    local value=$2
    log_info "Setting secret: $key"
    echo -n "$value" | databricks secrets put-secret "$SCOPE_NAME" "$key"
}

# Set secrets
set_secret "host" "$NEO4J_HOST"
set_secret "oauth_token_endpoint" "$OAUTH_TOKEN_ENDPOINT"
set_secret "oauth_client_id" "$OAUTH_CLIENT_ID"
set_secret "oauth_client_secret" "$OAUTH_CLIENT_SECRET"
set_secret "connection_name" "$UC_CONNECTION_NAME"
set_secret "jdbc_jar_path" "$JDBC_JAR_PATH"

# Set optional database (default is "neo4j")
if [[ -n "${NEO4J_DATABASE:-}" ]]; then
    set_secret "database" "$NEO4J_DATABASE"
fi

log_info "Done! Secrets configured in scope: $SCOPE_NAME"
echo ""
echo "Verify with:"
echo "  databricks secrets list-secrets $SCOPE_NAME"
echo ""
echo "Secrets created:"
echo "  host                 = $NEO4J_HOST"
echo "  oauth_token_endpoint = $OAUTH_TOKEN_ENDPOINT"
echo "  oauth_client_id      = $OAUTH_CLIENT_ID"
echo "  oauth_client_secret  = ********"
echo "  connection_name      = $UC_CONNECTION_NAME"
echo "  jdbc_jar_path        = $JDBC_JAR_PATH"
[[ -n "${NEO4J_DATABASE:-}" ]] && echo "  database             = $NEO4J_DATABASE"
