name: connector-build

on:
  push:
    branches:
      - main
    paths:
      - 'neo4j-unity-catalog-connector/**'
  pull_request:
    paths:
      - 'neo4j-unity-catalog-connector/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: neo4j-unity-catalog-connector
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('neo4j-unity-catalog-connector/pom.xml') }}-${{ github.sha }}
      - name: Clean and verify
        run: ./mvnw -q clean verify
